const A='./public/assets/';
const refImgs=['reference/1.png','reference/2.png','reference/3.png','reference/4.png','reference/5.png','reference/6.png','reference/7.png','reference/8.png'];
function shell(content){return '<section class="stage"><div class="design">'+content+'</div></section>'}
function rules(){return '<div class="rule-h"></div><div class="rule-v"></div>'}
function home(){return shell('<img class="home-bg" src="'+A+'main/image-1.png" alt="">'+rules()+'<div class="title">Sherry Zhang</div><div class="title home-title">Contextual Triangle Brief</div><div class="coordinates">31°14′N, 121°29′E</div><img class="home-ring-image" src="'+A+'figma/home-ring.png" alt=""><div class="home-hotspot" aria-label="Open navigation"></div><nav class="nav-options"><a href="#/universe">This Universe&nbsp;&nbsp;本宇宙</a><a href="#/parallel">Parallel Universes&nbsp;&nbsp;平行宇宙</a><a href="#/metaverse">The Metaverse&nbsp;&nbsp;元宇宙</a></nav>')}
function universe(){
 var strip='<img class="universe-strip" src="'+A+'figma/universe-strip-half.png" alt="">';
 return shell(rules()+'<a class="section-title title title-link" href="#/">This Universe&nbsp;&nbsp;本宇宙</a><div class="intro universe-intro">Work that I am proud of<br>Examples of work that I have already created, or helped create, which I am proud of.</div><div class="universe-orb a"></div><div class="universe-orb b"></div><div class="universe-orb c"></div><div class="work-track-wrap"><div class="work-track"><div class="work-sequence">'+strip+'</div><div class="work-sequence" aria-hidden="true">'+strip+'</div></div></div>');
}
function parallel(){
 var data=[
 ['Holly Herndon & Mat Dryhurst','The Call, 2024/10','parallel/figma/call.png',[]],
 ['Dunne & Raby','United Micro Kingdoms, 2012/13','parallel/figma/umk.png',['parallel/umk-landscape.jpg']],
 ['Simon Heijdens','Lightweeds, 2005','parallel/figma/lightweeds.png',['parallel/lightweeds.jpg']],
 ['Truth & Beauty','OECD Better Life Index, 2010','parallel/figma/oecd.png',['parallel/oecd.jpg']]
 ];
 var slots=data.map(function(d,i){var extra=d[3].map(function(src){return '<img class="parallel-panel-extra" src="'+A+src+'" alt="">'}).join('');return '<div class="slot" data-slot="'+i+'" role="button" tabindex="0" aria-expanded="false"><div class="parallel-panel" tabindex="0"><img class="parallel-panel-art" src="'+A+d[2]+'" alt="">'+extra+'<div class="parallel-panel-end" aria-hidden="true"></div></div><div class="parallel-label"><span>'+d[0]+'</span><span>'+d[1]+'</span></div><div class="parallel-dot"></div></div>'}).join('');
 return shell(rules()+'<a class="section-title title title-link" href="#/">Parallel Universes&nbsp;&nbsp;平行宇宙</a><div class="intro">Work of others that I wish I’d made<br>Examples of work not created by myself which represent the kind of work I would love to make myself.</div><div class="parallel-grid">'+slots+'</div>');
}
function metaGallery(files){return '<span class="meta-gallery">'+files.map(function(f){return '<img src="'+A+'meta/'+f+'" alt="">'}).join('')+'</span>'}
function metaverse(){return shell(rules()+'<a class="section-title title title-link" href="#/">The Metaverse&nbsp;&nbsp;元宇宙</a><div class="intro">Things outside of work that I think are interesting<br>Almost everything that I am passionate about, or find interesting, even if it doesn’t currently relate to my work.</div><div class="meta-wheel"><div class="meta-ring"></div><div class="meta-item i1"><div class="meta-upright exact-meta"><span class="meta-label">Science Fiction&Film</span><img src="'+A+'figma/metaverse-scifi.png" alt="Science Fiction & Film"></div></div><div class="meta-item i2"><div class="meta-upright exact-meta"><span class="meta-label">Crime&Deduction</span><img src="'+A+'figma/metaverse-crime.png" alt="Crime & Deduction"></div></div><div class="meta-item i3"><div class="meta-upright exact-meta"><span class="meta-label">Concert&Live House</span><img src="'+A+'figma/metaverse-concert.png" alt="Concert & Live House"></div></div><div class="meta-item i4"><div class="meta-upright"><span>Animation</span>'+metaGallery(['2.png','10.png','13.png','17.png'])+'</div></div><div class="meta-item i5"><div class="meta-upright"><span>Photography</span>'+metaGallery(['4.png','11.png','12.png','8.png'])+'</div></div></div>')}
function fitDesign(){var d=document.querySelector('.design');if(!d)return;var s=Math.min(window.innerWidth/3840,window.innerHeight/2160);d.style.transform='translate(-50%,-50%) scale('+s+')'}
function render(){var p=location.hash.replace('#','')||'/';document.getElementById('app').innerHTML=p==='/universe'?universe():p==='/parallel'?parallel():p==='/metaverse'?metaverse():home();fitDesign();var hotspot=document.querySelector('.home-hotspot');if(hotspot){var design=document.querySelector('.design');var nav=document.querySelector('.nav-options');hotspot.addEventListener('mouseenter',function(){design.classList.add('nav-revealed')});document.querySelector('.stage').addEventListener('click',function(e){if(!hotspot.contains(e.target)&&!nav.contains(e.target))design.classList.remove('nav-revealed')})}function toggleSlot(slot){var grid=slot.closest('.parallel-grid');var wasOpen=slot.classList.contains('open');document.querySelectorAll('.slot').forEach(function(s){s.classList.remove('open');s.setAttribute('aria-expanded','false');var q=s.querySelector('.parallel-panel');if(q)q.classList.remove('open')});grid.classList.remove('open-0','open-1','open-2','open-3');if(!wasOpen){slot.classList.add('open');slot.setAttribute('aria-expanded','true');slot.querySelector('.parallel-panel').classList.add('open');grid.classList.add('open-'+slot.dataset.slot)}}document.querySelectorAll('.slot').forEach(function(slot){slot.addEventListener('click',function(e){if(slot.classList.contains('open')&&e.target.closest('.parallel-panel'))return;toggleSlot(slot)});slot.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();toggleSlot(slot)}})});document.querySelectorAll('.parallel-panel').forEach(function(panel){panel.addEventListener('wheel',function(e){e.preventDefault();panel.scrollTop+=e.deltaY},{passive:false});panel.addEventListener('keydown',function(e){if(e.key==='PageDown'||e.key==='ArrowDown'){e.preventDefault();panel.scrollTop+=e.key==='PageDown'?panel.clientHeight*.8:80}if(e.key==='PageUp'||e.key==='ArrowUp'){e.preventDefault();panel.scrollTop-=e.key==='PageUp'?panel.clientHeight*.8:80}})})}
window.addEventListener('hashchange',render);window.addEventListener('resize',fitDesign);render();