const A='./public/assets/';
const refImgs=['reference/1.png','reference/2.png','reference/3.png','reference/4.png','reference/5.png','reference/6.png','reference/7.png','reference/8.png'];
function shell(content){return '<section class="stage"><div class="design">'+content+'</div></section>'}
function rules(){return '<div class="rule-h"></div><div class="rule-v"></div>'}
function home(){return shell('<img class="home-bg" src="'+A+'main/image-1.png" alt="">'+rules()+'<div class="title">Sherry Zhang</div><div class="title home-title">Contextual Triangle Brief</div><div class="coordinates">31°14′N, 121°29′E</div><div class="home-ring"><span class="pointer"></span></div><div class="home-hotspot" aria-label="Open navigation"></div><nav class="nav-options"><a href="#/universe">This Universe&nbsp;&nbsp;本宇宙</a><a href="#/parallel">Parallel Universes&nbsp;&nbsp;平行宇宙</a><a href="#/metaverse">The Metaverse&nbsp;&nbsp;元宇宙</a></nav>')}
function workGallery(files){return '<div class="work-gallery">'+files.map(function(f){return '<img src="'+A+'work/'+f+'" alt="">'}).join('')+'</div>'}
function workFeature(hero,title,tags,description,video){return '<article class="work-card"><div class="work-hero"><img src="'+A+'work/'+hero+'" alt=""></div><div class="work-copy"><h2>'+title+'</h2><p>'+tags+'</p><p>'+description+'</p>'+(video?'<a href="'+video+'" target="_blank" rel="noreferrer">Video Link</a>':'')+'</div></article>'}
function universe(){
 var one=[
 workFeature('1.png','The Post-Linguistic Era','Nonverbal Expression | Tactile Instrument | Performance Art | Interactive Installation','An interactive sound installation built from custom stainless-steel gesture plates, capacitive sensing and synthesized sound. The work explores communication, ambiguity and the loneliness produced by failed understanding.','https://youtu.be/MjTHjzha6Yo'),
 '<article class="work-card gallery-card">'+workGallery(['3.png','4.jpg','5.png','7.png','8.jpg','12.jpg','13.jpg','18.png'])+'</article>',
 workFeature('6.jpg','Signal Lag','Installation | Embedded Electronics | Emotional Asymmetry | Controlled Speech','A media installation combining character displays, TFT modules and projected interview footage. Fragmented police task messages and delayed family replies reveal the emotional architecture of distance, protocol and restrained communication.','https://youtu.be/PzeDgDzhNWI'),
 '<article class="work-card gallery-card">'+workGallery(['10.jpg','11.jpg','14.jpg','15.jpg','16.jpg','19.jpg','20.jpg'])+'</article>',
 workFeature('17.jpg','Synthetic Plant Cultivation Platform','Architectural & Internal Structure Design','A speculative cultivation platform combining modular environments, automated resource circulation and remote monitoring for synthetic plant ecologies.',''),
 '<article class="work-card gallery-card">'+workGallery(['9.png','2.png'])+'</article>'
 ].join('');
 return shell(rules()+'<a class="section-title title title-link" href="#/">This Universe&nbsp;&nbsp;本宇宙</a><div class="intro universe-intro">Work that I am proud of<br>Examples of work that I have already created, or helped create, which I am proud of.</div><div class="universe-orb a"></div><div class="universe-orb b"></div><div class="universe-orb c"></div><div class="work-track-wrap"><div class="work-track">'+one+one+'</div></div>');
}
function parallel(){
 var data=[
 ['Holly Herndon & Mat Dryhurst','The Call, 2024/10','The Call centres on developing new protocols and materials for creating choral AI models. Community choirs become participants in a process connecting collective voice, model training and cultural authorship.'],
 ['Dunne & Raby','United Micro Kingdoms, 2012/13','United Micro Kingdoms presents a fictional future for the United Kingdom through four competing social, ideological, technological and economic models.'],
 ['Simon Heijdens','Lightweeds, 2005','Lightweeds is an ecosystem of living digital plants that respond to weather, movement and the changing use of architecture, allowing projected vegetation to inhabit the building as a responsive presence.'],
 ['Truth & Beauty','OECD Better Life Index, 2010','The OECD Better Life Index visualises wellbeing beyond GDP and lets people compare countries by adjusting the importance of different dimensions of life.']
 ];
 var callImgs=refImgs.map(function(x){return '<img src="'+A+x+'" alt="">'}).join('');
 var contents=[
 '<p>'+data[0][2]+'</p><div class="parallel-images">'+callImgs+'</div>',
 '<div class="dunne-icons"><span>▦</span><span>◎◎</span><span>◒◒</span><span>◯</span></div><div class="quadrant"><span>Communo-nuclearists</span><span>Digitarians</span><span>Bioliberals</span><span>Anarcho-evolutionists</span></div><p>'+data[1][2]+'</p>',
 '<p>'+data[2][2]+'</p>',
 '<p>'+data[3][2]+'</p>'
 ];
 var slots=data.map(function(d,i){return '<div class="slot" data-slot="'+i+'"><div class="parallel-panel">'+contents[i]+'</div><div class="parallel-label"><span>'+d[0]+'</span><span>'+d[1]+'</span></div><div class="parallel-dot"></div></div>'}).join('');
 return shell(rules()+'<a class="section-title title title-link" href="#/">Parallel Universes&nbsp;&nbsp;平行宇宙</a><div class="intro">Work of others that I wish I’d made<br>Examples of work not created by myself which represent the kind of work I would love to make myself.</div><div class="parallel-grid">'+slots+'</div>');
}
function metaGallery(files){return '<span class="meta-gallery">'+files.map(function(f){return '<img src="'+A+'meta/'+f+'" alt="">'}).join('')+'</span>'}
function metaverse(){return shell(rules()+'<a class="section-title title title-link" href="#/">The Metaverse&nbsp;&nbsp;元宇宙</a><div class="intro">Things outside of work that I think are interesting<br>Almost everything that I am passionate about, or find interesting, even if it doesn’t currently relate to my work.</div><div class="meta-ring"><div class="meta-item i1"><span>Science Fiction & Film</span>'+metaGallery(['5.png','16.png','6.png'])+'</div><div class="meta-item i2"><span>Crime & Deduction</span>'+metaGallery(['18.png','7.png'])+'</div><div class="meta-item i3"><span>Concert & Live House</span>'+metaGallery(['15.png','9.jpg','19.jpg','20.png'])+'</div><div class="meta-item i4"><span>Animation</span>'+metaGallery(['2.png','10.png','13.png','17.png'])+'</div><div class="meta-item i5"><span>Photography</span>'+metaGallery(['4.png','11.png','12.png'])+'</div></div>')}
function fitDesign(){var d=document.querySelector('.design');if(!d)return;var s=Math.min(window.innerWidth/3840,window.innerHeight/2160);d.style.transform='translate(-50%,-50%) scale('+s+')'}
function render(){var p=location.hash.replace('#','')||'/';document.getElementById('app').innerHTML=p==='/universe'?universe():p==='/parallel'?parallel():p==='/metaverse'?metaverse():home();fitDesign();var hotspot=document.querySelector('.home-hotspot');if(hotspot){var design=document.querySelector('.design');var nav=document.querySelector('.nav-options');hotspot.addEventListener('mouseenter',function(){design.classList.add('nav-revealed')});document.querySelector('.stage').addEventListener('click',function(e){if(!hotspot.contains(e.target)&&!nav.contains(e.target))design.classList.remove('nav-revealed')})}document.querySelectorAll('.parallel-label').forEach(function(el){el.addEventListener('click',function(){var slot=el.closest('.slot');var grid=el.closest('.parallel-grid');var wasOpen=slot.classList.contains('open');document.querySelectorAll('.slot').forEach(function(s){s.classList.remove('open');var q=s.querySelector('.parallel-panel');if(q)q.classList.remove('open')});grid.classList.remove('open-0','open-1','open-2','open-3');if(!wasOpen){slot.classList.add('open');slot.querySelector('.parallel-panel').classList.add('open');grid.classList.add('open-'+slot.dataset.slot)}})})}
window.addEventListener('hashchange',render);window.addEventListener('resize',fitDesign);render();